services:
    db:
      image: "docker.io/library/mariadb:11"
      environment: 
        MYSQL_ROOT_PASSWORD: "secret"
        MYSQL_DATABASE: "mitglieder"
        MYSQL_USER: "mitglieder"
        MYSQL_PASSWORD: "mitglieder"
      ports: 
        - "3306"
      volumes:
        - "./db:/var/lib/mysql:cached"
    web:
      image: "ghcr.io/wabuehamm/web.members:latest"
      volumes:
        - "./site:/var/www/localhost/htdocs:cached"
        - "./data:/srv/elgg_data:cached"
      ports:
        - "${PORT:-8443}:8443"
