version: "3.7"
services:
    db:
      image: "mariadb:10"
      environment: 
        MYSQL_ROOT_PASSWORD: "secret"
        MYSQL_DATABASE: "mitglieder"
        MYSQL_USER: "mitglieder"
        MYSQL_PASSWORD: "mitglieder"
    web:
      build:
        context: "."
      image: "mitglieder-web:latest"
      volumes:
        - "./export/site:/var/www/localhost/htdocs:delegated"
        - "./export/data:/srv/elgg_data:delegated"
        - "./export/db:/db:delegated"
      ports:
        - "8443:8443"
    selenium-hub:
      image: "selenium/hub:3.141.59-titanium"
      ports:
        - "4444:4444"
    selenium-chrome:
      image: "selenium/node-chrome-debug:3.141.59-titanium"
      environment: 
        HUB_HOST: "selenium-hub"
      ports:
        - "5901:5900"
      volumes: 
      - "./selenium:/home/seluser/Downloads"
    selenium-firefox:
      image: "selenium/node-firefox-debug:3.141.59-titanium"
      environment: 
        HUB_HOST: "selenium-hub"
      ports:
        - "5902:5900"
      volumes: 
      - "./selenium:/home/seluser/Downloads"
